# Generated by Django 4.2 on 2023-06-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_league_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapid_fixture_id', models.IntegerField()),
                ('fixture_date', models.DateTimeField()),
                ('referee', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=10, null=True)),
                ('fixture_round', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='football.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='football.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.league')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.teamvenue')),
            ],
            options={
                'db_table': 'fixture',
                'unique_together': {('rapid_fixture_id',)},
            },
        ),
        migrations.CreateModel(
            name='FixtureStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win', models.BooleanField(default=False, null=True)),
                ('away_win', models.BooleanField(default=False, null=True)),
                ('home_goals', models.IntegerField(null=True)),
                ('away_goals', models.IntegerField(null=True)),
                ('home_ht_score', models.IntegerField(null=True)),
                ('away_ht_score', models.IntegerField(null=True)),
                ('home_ft_score', models.IntegerField(null=True)),
                ('away_ft_score', models.IntegerField(null=True)),
                ('home_et_score', models.IntegerField(blank=True, null=True)),
                ('away_et_score', models.IntegerField(blank=True, null=True)),
                ('home_et_penalties', models.IntegerField(blank=True, null=True)),
                ('away_et_penalties', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.fixture')),
            ],
            options={
                'db_table': 'fixture_stats',
                'unique_together': {('fixture',)},
            },
        ),
    ]
