# Generated by Django 4.2 on 2023-06-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_fixture_fixturestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggHomeFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('goals_for', models.IntegerField(null=True)),
                ('goals_against', models.IntegerField(null=True)),
                ('ht_score_for', models.IntegerField(null=True)),
                ('ht_score_against', models.IntegerField(null=True)),
                ('ft_score_for', models.IntegerField(null=True)),
                ('ft_score_against', models.IntegerField(null=True)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.team')),
            ],
            options={
                'db_table': 'agg_home_fixture',
                'unique_together': {('season', 'home_team')},
            },
        ),
        migrations.CreateModel(
            name='AggAwayFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('goals_for', models.IntegerField(null=True)),
                ('goals_against', models.IntegerField(null=True)),
                ('ht_score_for', models.IntegerField(null=True)),
                ('ht_score_against', models.IntegerField(null=True)),
                ('ft_score_for', models.IntegerField(null=True)),
                ('ft_score_against', models.IntegerField(null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.team')),
            ],
            options={
                'db_table': 'agg_away_fixture',
                'unique_together': {('season', 'away_team')},
            },
        ),
    ]
