# Generated by Django 5.0.3 on 2024-03-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0014_alter_aggawayfixture_season_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="season",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.PROTECT,
                to="football.season",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="season",
            field=models.ForeignKey(
                default=15,
                on_delete=django.db.models.deletion.PROTECT,
                to="football.season",
            ),
            preserve_default=False,
        ),
    ]
