# Generated by Django 5.0.3 on 2024-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0015_alter_fixture_season_alter_playerstats_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="referee",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
