# Generated by Django 5.0.3 on 2024-03-08 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0016_alter_fixture_referee"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixturePlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes", models.IntegerField(null=True)),
                ("position", models.CharField(max_length=50, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("captain", models.BooleanField(default=False)),
                ("offsides", models.IntegerField(null=True)),
                ("shots", models.IntegerField(null=True)),
                ("shots_on_target", models.IntegerField(null=True)),
                ("goals", models.IntegerField(null=True)),
                ("assists", models.IntegerField(null=True)),
                ("passes", models.IntegerField(null=True)),
                ("key_passes", models.IntegerField(null=True)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("tackles", models.IntegerField(null=True)),
                ("blocks", models.IntegerField(null=True)),
                ("interceptions", models.IntegerField(null=True)),
                ("duels", models.IntegerField(null=True)),
                ("duels_won", models.IntegerField(null=True)),
                ("dribbles", models.IntegerField(null=True)),
                ("dribble_success", models.IntegerField(null=True)),
                ("dribble_past", models.IntegerField(null=True)),
                ("fouls_drawn", models.IntegerField(null=True)),
                ("fouls_committed", models.IntegerField(null=True)),
                ("yellow_cards", models.IntegerField(null=True)),
                ("yellow_red_cards", models.IntegerField(null=True)),
                ("red_cards", models.IntegerField(null=True)),
                ("penalty_won", models.IntegerField(null=True)),
                ("penalty_committed", models.IntegerField(null=True)),
                ("penalty_scored", models.IntegerField(null=True)),
                ("penalty_missed", models.IntegerField(null=True)),
                ("penalty_saved", models.IntegerField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="football.fixture",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="football.player",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="football.team"
                    ),
                ),
            ],
            options={
                "db_table": "fixture_player_stats",
                "unique_together": {("fixture", "team", "player")},
            },
        ),
    ]
