# Generated by Django 5.0.3 on 2024-03-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("football", "0017_fixtureplayerstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixtureplayerstats",
            name="conceded",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fixtureplayerstats",
            name="number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fixtureplayerstats",
            name="saves",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="image",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
