# Generated by Django 5.0.3 on 2024-06-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_fixture_timestamp_fixture_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(null=True)),
                ('losses', models.IntegerField(null=True)),
                ('draws', models.IntegerField(null=True)),
                ('goals_for', models.IntegerField(null=True)),
                ('goals_against', models.IntegerField(null=True)),
                ('ht_score_for', models.IntegerField(null=True)),
                ('ht_score_against', models.IntegerField(null=True)),
                ('ft_score_for', models.IntegerField(null=True)),
                ('ft_score_against', models.IntegerField(null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.team')),
            ],
            options={
                'db_table': 'agg_fixture',
                'unique_together': {('season', 'team')},
            },
        ),
    ]
